image: elixir:1.13
build:
  stage: build
  script:
    - apt-get update
    - apt-get install -y build-essential automake autoconf pkg-config bc m4 unzip zip curl git libssl-dev libncurses5-dev erlang-inets erlang-os-mon erlang-runtime-tools erlang-ssl erlang-dev python3 ca-certificates cmake
    - mix local.hex --force
    - mix local.rebar --force
    - mix deps.get
    - mix deps.compile
    - MAKE_BUILD_FLAGS="-j$(nproc)" mix compile

