name: CI

on:
  pull_request:
  push:
    branches:
      - main
    paths-ignore:
      - '**/README.md'

  workflow_dispatch:

jobs:
  mix_test:
    runs-on: ubuntu-20.04
    env:
      MIX_ENV: test

    name: Elixir ${{ matrix.pair.elixir }} / OTP ${{ matrix.pair.otp }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - pair:
              elixir: 1.11.2
              otp: 23.1.4
          - pair:
              elixir: 1.12.3
              otp: 24.1.5

    steps:
      - uses: actions/checkout@v2

      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.pair.otp}}
          elixir-version: ${{matrix.pair.elixir}}
      
      - name: Install system dependecies
        run: sudo apt-get install -y libopenblas64-openmp-dev libgmp-dev libatlas-base-dev build-essential \
             autoconf pkg-config bc m4 unzip zip curl libssl-dev libncurses5-dev \
             erlang-os-mon erlang-runtime-tools erlang-ssl erlang-dev
      
      - name: Install Numpy (compile-time dependency)
        run: pip install -U numpy pyyaml setuptools future six requests dataclasses typing_extensions

      - name: Install Dependencies
        run: mix deps.get

      - run: mix deps.compile

      - run: mix compile
