name: linux-precompile

on:
  push:
    tags:
      - '*-dev'
      - '*-prod'
      - '*-dev-linux'

jobs:
  mix_test:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - pair:
              arch_name: x86_64
              deb_arch: amd64
              cmake_toolchain_file: ""
          - pair:
              arch_name: aarch64
              deb_arch: arm64
              cmake_toolchain_file: cc_toolchain/linux-aarch64.cmake
          - pair:
              arch_name: armv7l
              deb_arch: armhf
              cmake_toolchain_file: cc_toolchain/linux-armv7l.cmake

    steps:
      - uses: actions/checkout@v2

      - uses: erlef/setup-beam@v1
        if: ${{ matrix.pair.arch == 'x86_64' }}
        with:
          otp-version: "24.3"
          elixir-version: "1.13.3"

      - name: Install system dependecies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential automake autoconf pkg-config bc m4 unzip zip curl git libssl-dev gzip libncurses5-dev python3 ca-certificates

      - name: Install system dependecies (aarch64)
        if: ${{ matrix.pair.arch_name == 'aarch64' }}
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-aarch64-linux-gnu g++-aarch64-linux-gnu

      - name: Install system dependecies (armv7l)
        if: ${{ matrix.pair.arch_name == 'armv7l' }}
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-arm-linux-gnueabihf g++-arm-linux-gnueabihf

      - name: Create precompiled library
        run: |
          mix deps.get
          mix compile
          export TOOLCHAIN_FILE=${{ matrix.pair.cmake_toolchain_file }}
          export PKG_NAME=evision-linux-${{ matrix.pair.arch_name }}-0.1.0-dev
          mkdir -p "${PKG_NAME}"
          cp -a _build/dev/lib/evision/priv "${PKG_NAME}"
          cp -a lib/generated "${PKG_NAME}"
          tar -czf "${PKG_NAME}.tar.gz" "${PKG_NAME}"
          rm -rf "${PKG_NAME}"
          ls -lah "${PKG_NAME}.tar.gz"
          mkdir -p artifacts
          mv "${PKG_NAME}.tar.gz" artifacts

      - uses: softprops/action-gh-release@v1
        with:
          tag_name: 0.1.0-dev
          files: artifacts/*.tar.gz
