name: linux-arm64

on:
  pull_request:
  push:
    branches:
      - main
    paths-ignore:
      - '**/README.md'
  workflow_dispatch:

jobs:
  mix_test:
    runs-on: ubuntu-20.04
    env:
      MIX_ENV: test

    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: aarch64
            distro: ubuntu20.04

    steps:
      - uses: actions/checkout@v2
      - uses: uraimo/run-on-arch-action@v2.0.5
        name: Build artifact
        id: build
        with:
          arch: ${{ matrix.arch }}
          distro: ${{ matrix.distro }}
          
          shell: /bin/bash
          install: |
            apt-get update -q -y
            apt-get install -y build-essential automake autoconf pkg-config bc m4 unzip zip wget curl git libssl-dev libncurses5-dev erlang-inets erlang-os-mon erlang-runtime-tools erlang-ssl erlang-dev python3 ca-certificates erlang-parsetools
            wget https://github.com/elixir-lang/elixir/releases/download/v1.12.3/Precompiled.zip -O Precompiled.zip
            unzip Precompiled.zip
            export PATH="$(pwd)/Precompiled/bin:${PATH}"
            mix local.hex --force
            mix local.rebar --force

          run: |
            export PATH="$(pwd)/Precompiled/bin:${PATH}"
            mix deps.get && mix deps.compile
            CMAKE_BUILD_FLAGS="-j$(nproc)" mix compile
