name: macos-x86_64

on:
  pull_request:
    paths-ignore:
      - '**/README.md'
      - 'examples/**'
      - 'nerves/**'
      - 'Makefile.win'
      - '.github/FUNDING.yml'
      - '.github/workflows/nerves-*.yml'
      - '.github/workflows/linux-*.yml'
      - '.github/workflows/windows-*.yml'
      - '.github/workflows/test-*.yml'
  push:
    tags:
      - '*-dev'
      - '*-prod'
    branches:
      - main
      - test-*
    paths-ignore:
      - '**/README.md'
      - 'examples/**'
      - 'nerves/**'
      - 'Makefile.win'
      - '.github/FUNDING.yml'
      - '.github/workflows/nerves-*.yml'
      - '.github/workflows/linux-*.yml'
      - '.github/workflows/windows-*.yml'
      - '.github/workflows/test-*.yml'
  workflow_dispatch:

jobs:
  mix_test:
    runs-on: macos-11
    strategy:
      fail-fast: false
      matrix:
        include:
          - pair:
              opencv_ver: 4.5.5
              upload: false
              mix_env: test
              evision_version: 0.1.0-dev
          - pair:
              opencv_ver: 4.5.5
              upload: false
              mix_env: test
              evision_version: 0.1.0-dev

    steps:
      - uses: actions/checkout@v2
      
      - name: Install Erlang and Elixir
        run: |
          brew install erlang
          brew install elixir
          brew install ffmpeg@4
          brew link ffmpeg@4
          mix local.hex --force
          mix local.rebar --force

      - name: Build precompiled library
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          export OPENCV_VER=${{ matrix.pair.opencv_ver }}
          export MIX_ENV=${{ matrix.pair.mix_env }}
          mix deps.get
          NPROC="$(sysctl -a | grep 'hw.ncpu' | awk '{print $2}')"
          MAKE_BUILD_FLAGS="-j${NPROC}" mix compile

      - name: mix compile for CI test
        run: |
          if [ "${{ matrix.pair.mix_env }}" = "test" ]; then
            export OPENCV_VER=${{ matrix.pair.opencv_ver }}
            export MIX_ENV=${{ matrix.pair.mix_env }}
            mix deps.get
            NPROC="$(sysctl -a | grep 'hw.ncpu' | awk '{print $2}')"
            MAKE_BUILD_FLAGS="-j${NPROC}" mix compile
          fi

      - name: Mix Test
        run: |
          if [ "${{ matrix.pair.mix_env }}" = "test" ]; then
            export OPENCV_VER=${{ matrix.pair.opencv_ver }}
            mix test --include require_downloading --include require_ffmpeg
          fi

      - name: Create precompiled package
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          if [ "${{ matrix.pair.upload }}" = "true" ]; then
            export PKG_NAME=evision-macos-x86_64-${{ matrix.pair.evision_version }}
            echo "pkg_name=${PKG_NAME}.tar.gz" >> $GITHUB_ENV
            mkdir -p "${PKG_NAME}"
            cp -a _build/${{ matrix.pair.mix_env }}/lib/evision/priv "${PKG_NAME}"
            cp -a lib/generated "${PKG_NAME}"
            tar -czf "${PKG_NAME}.tar.gz" "${PKG_NAME}"
            rm -rf "${PKG_NAME}"
            ls -lah "${PKG_NAME}.tar.gz"
          else
            echo "skipped"
          fi

      - uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ${{ env.pkg_name }}
