name: macos-precompile

on:
  push:
    tags:
      - '*-dev'
      - '*-prod'
  workflow_dispatch:

jobs:
  mix_test:
    runs-on: macos-11
    env:
      MIX_ENV: dev
      EVISION_VERSION: 0.1.0-dev

    steps:
      - uses: actions/checkout@v2

      - name: Install Erlang and Elixir
        run: |
          brew install erlang
          brew install elixir
          brew install ffmpeg@4
          brew link ffmpeg@4
          mix local.hex --force
          mix local.rebar --force

      - name: Create precompiled library
        run: |
          mix deps.get
          mix compile
          export PKG_NAME=evision-darwin-x86_64-${EVISION_VERSION}
          echo "pkg_name=${PKG_NAME}.tar.gz" >> $GITHUB_ENV
          mkdir -p "${PKG_NAME}"
          cp -a _build/${MIX_ENV}/lib/evision/priv "${PKG_NAME}"
          cp -a lib/generated "${PKG_NAME}"
          tar -czf "${PKG_NAME}.tar.gz" "${PKG_NAME}"
          rm -rf "${PKG_NAME}"
          ls -lah "${PKG_NAME}.tar.gz"
          mkdir -p artifacts
          mv "${PKG_NAME}.tar.gz" artifacts

      - uses: softprops/action-gh-release@v1
        with:
          files: artifacts/*.tar.gz
