name: windows-x86_64

on:
  pull_request:
  push:
    branches:
      - main
      - test-*
    paths-ignore:
      - '**/README.md'
      - 'examples/**'
      - 'nerves/**'
      - 'Makefile'
      - '.github/FUNDING.yml'
      - '.github/workflows/nerves-*'
      - '.github/workflows/linux-*.yml'
      - '.github/workflows/macos-*.yml'
      - '.github/workflows/test-*.yml'
  workflow_dispatch:

jobs:
  mix_test:
    runs-on: windows-latest
    env:
      MIX_ENV: test

    strategy:
      fail-fast: false
      matrix:
        include:
          - pair:
              elixir: 1.13.2
              otp: 24.2
              opencv_ver: 4.5.4
          - pair:
              elixir: 1.13.2
              otp: 24.2
              opencv_ver: 4.5.5

    steps:
      - uses: actions/checkout@v2
      
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.pair.otp}}
          elixir-version: ${{matrix.pair.elixir}}
      
      - name: Setup dependencies
        run: |
          mix local.hex --force
          mix local.rebar --force

      - name: Mix Compile
        run: |
          set OPENCV_VER=${{ matrix.pair.opencv_ver }}
          set MAKE=nmake
          mix deps.get
          del /f Makefile
          mix compile

      - name: Mix Test
        run: |
          set OPENCV_VER=${{ matrix.pair.opencv_ver }}
          set MAKE=nmake
          mix test --include require_downloading --include require_ffmpeg
